[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_escrow = "2dupZTbJ6jcBDRT3wa1A5JADh2q4hWLgTSf8dCCQSvoA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 10000000

[test.validator]
url = "https://api.devnet.solana.com"
bind_address = "0.0.0.0"
rpc_port = 8899                    


[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"

